# -*- coding: utf-8 -*-
"""unsupervised code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z4SFKzvWKujjaLbLTD8UV6EaFDiuv9I4
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.cluster import KMeans


import warnings
warnings.filterwarnings('ignore')

df=pd.read_csv('https://raw.githubusercontent.com/dsrscientist/dataset3/main/Mall_customers.csv')
df

x=df.iloc[:,3:]

x

wcss=[]

for i in range(1,11):
  kmeans=KMeans(n_clusters=i,init='k-means++')
  kmeans.fit(x)
  wcss.append(kmeans.inertia_)

plt.plot(range(1,11),wcss,marker='x')
plt.title=('the elbow methd')
plt.xlabel('no. of cluster')
plt.ylabel('wcss')
plt.show()

kmeans = KMeans(n_clusters=5,init='k-means++')
y_kmeans= kmeans.fit_predict(x)
print(y_kmeans)
#n_clusters=5 means here is 5 gropus present

kmeans.labels_

kmeans.cluster_centers_

x[y_kmeans==0]
#gropu1

x[y_kmeans==2]

dd= pd.DataFrame(data=x[y_kmeans==0])
dd

dd.to_csv('filekmean_group0.csv')
import pickle
filename='filekmean.pickle'
pickle.dump(kmeans,open(filename,'wb'))

df

ds=pd.DataFrame(data=df)
ds

ds['group_cluster']=pd.DataFrame(data=kmeans.labels_)
ds

