# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EyZi7xRrntgojoBuJUJNS07stRoE09DE
"""

import re

sample_text = 'Python Exercises, PHP exercises.'
result = re.sub(r'[ ,.]', ':', sample_text)
print(result)

"""Question no 2"""

import re

sample_text = 'apple banana elephant ant eagle'
result = re.findall(r'\b[ae]\w+', sample_text)
print(result)

"""Question no 3"""

import re

def find_long_words(text):
    pattern = re.compile(r'\b\w{4,}\b')
    return pattern.findall(text)

sample_text = 'This is a sample sentence with some longer words like Python and exercise.'
result = find_long_words(sample_text)
print(result)

"""Question no 4"""

import re

def find_words_with_length(text):
    pattern = re.compile(r'\b\w{3,5}\b')
    return pattern.findall(text)

sample_text = 'This is a sample sentence with different word lengths.'
result = find_words_with_length(sample_text)
print(result)

"""Question no 5"""

import re

def remove_parentheses(strings):
    pattern = re.compile(r'\([^)]*\)')
    return [pattern.sub('', s) for s in strings]

sample_text = ["example (.com)", "hr@fliprobo (.com)", "github (.com)", "Hello (Data Science World)", "Data (Scientist)"]
result = remove_parentheses(sample_text)
for r in result:
    print(r)

"""Question no 6"""

import re

def remove_parentheses_from_file(file_name):
    with open(file_name, 'r') as file:
        strings = file.readlines()
    return remove_parentheses(strings)

file_name = 'sample_text.txt'
result = remove_parentheses_from_file(file_name)
for r in result:
    print(r)

"""Question no 7"""

import re

sample_text = "ImportanceOfRegularExpressionsInPython"
result = re.findall(r'[A-Z][a-z]*', sample_text)
print(result)

"""Question no 8"""

import re

sample_text = "RegularExpression1IsAn2ImportantTopic3InPython"
result = re.sub(r'(\d)([A-Z])', r'\1 \2', sample_text)
print(result)

"""Question no 9"""

import re

sample_text = "RegularExpression1IsAn2ImportantTopic3InPython"
result = re.sub(r'(\d|[A-Z])([A-Z])', r'\1 \2', sample_text)
print(result)

"""Question no 10"""

import re

def extract_emails_from_file(file_name):
    with open(file_name, 'r') as file:
        text = file.read()
    pattern = re.compile(r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b')
    return pattern.findall(text)

file_name = 'email_text.txt'
result = extract_emails_from_file(file_name)
print(result)

"""Qestion no 11"""

import re

def is_valid_string(text):
    return bool(re.match(r'^[A-Za-z0-9_]*$', text))

sample_text = "Valid_string123"
print(is_valid_string(sample_text))

"""Question no 12"""

import re

def starts_with_number(text, number):
    return bool(re.match(r'^' + str(number), text))

sample_text = "123Hello"
number_to_match = 123
print(starts_with_number(sample_text, number_to_match))

Question no 13

import re

def remove_leading_zeros(ip_address):
    return re.sub(r'\b0+(\d)', r'\1', ip_address)

ip_address = "192.010.002.001"
result = remove_leading_zeros(ip_address)
print(result)

"""Question 14"""

import re

def extract_dates_from_file(file_name):
    with open(file_name, 'r') as file:
        text = file.read()
    pattern = re.compile(r'(\b[A-Z][a-z]+ \d{1,2}(?:st|nd|rd|th)? \d{4}\b)')
    return pattern.findall(text)

file_name = 'date_text.txt'
result = extract_dates_from_file(file_name)
print(result)

"""Question 15"""

import re

sample_text = 'The quick brown fox jumps over the lazy dog.'
search_words = ['fox', 'dog', 'horse']

for word in search_words:
    if re.search(r'\b' + re.escape(word) + r'\b', sample_text):
        print(f"'{word}' found in the text.")
    else:
        print(f"'{word}' not found in the text.")

"""Question 16"""



import re

sample_text = 'The quick brown fox jumps over the lazy dog.'
search_word = 'fox'

match = re.search(search_word, sample_text)
if match:
    print(f"'{search_word}' found at position {match.start()}.")
else:
    print(f"'{search_word}' not found in the text.")

"""Question 17"""

import re

sample_text = 'Python exercises, PHP exercises, C# exercises'
pattern = 'exercises'
result = re.findall(pattern, sample_text)
print(result)

"""Question 18"""

import re

sample_text = 'Python exercises, PHP exercises, C# exercises'
pattern = 'exercises'

matches = [(match.group(), match.start()) for match in re.finditer(pattern, sample_text)]
print(matches)

"""Question 19"""

import re

def convert_date_format(date):
    match = re.match(r'(\d{4})-(\d{2})-(\d{2})', date)
    if match:
        year, month, day = match.groups()
        return f'{day}-{month}-{year}'
    else:
        return date

date = "2023-10-07"
new_date = convert_date_format(date)
print(new_date)

"""Question 20"""

import re

sample_text = "01.12 0132.123 2.31875 145.8 3.01 27.25 0.25"
result = re.findall(r'\b\d+\.\d{1,2}\b', sample_text)
print(result)

"""Question 21"""

import re

sample_text = "The price of item1 is $20 and item2 is $15."
matches = [(match.group(), match.start()) for match in re.finditer(r'\$\d+', sample_text)]
for match, position in matches:
    print(f"{match} found at position {position}.")

"""Question 22"""

import re

sample_text = 'My marks in each semester are: 947, 896, 926, 524, 734, 950, 642'
numbers = re.findall(r'\d+', sample_text)
largest_number = max(numbers, key=int)
print(largest_number)

"""Question 23"""

import re

sample_text = "RegularExpressionIsAnImportantTopicInPython"
result = re.sub(r'([A-Z])', r' \1', sample_text)
print(result.strip())

"""Question 24"""

import re

sample_text = "This Is a Regular Expression Example"
result = re.findall(r'[A-Z][a-z]*', sample_text)
print(result)

"""Question 25"""

import re

sample_text = "Hello hello world world"
result = re.sub(r'\b(\w+)\s+\1\b', r'\1', sample_text)
print(result)

"""Question 26"""

import re

def ends_with_alphanumeric(text):
    return bool(re.match(r'^.*[a-zA-Z0-9]$', text))

sample_text = "This is a test1"
print(ends_with_alphanumeric(sample_text))

"""Question 27"""

import re

sample_text = "RT @kapil_kausik: #Doltiwal I mean #xyzabc is 'hurt' by #Demonetization"
hashtags = re.findall(r'#\w+', sample_text)
print(hashtags)

"""Question 28"""

import re

sample_text = "@Jags123456 Bharat band on 28??<ed><U+00A0><U+00BD><ed><U+00B8><U+0082>Those who are protesting #demonetization"
result = re.sub(r'<U\+\w+>', '', sample_text)
print(result)

"""Question 29"""

import re

def extract_dates_from_file(file_name):
    with open(file_name, 'r') as file:
        text = file.read()
    pattern = re.compile(r'\b\d{2}-\d{2}-\d{4}\b')
    return pattern.findall(text)

file_name = 'date_text.txt'
result = extract_dates_from_file(file_name)
print(result)

"""Question 30"""

import re

def remove_words_by_length(text):
    pattern = re.compile(r'\b\w{2,4}\b')
    return pattern.sub('', text)

sample_text = "The following example creates an ArrayList with a capacity of 50 elements. 4 elements are then added to the ArrayList and the ArrayList is trimmed accordingly."
result = remove_words_by_length(sample_text)
print(result)